<?php

namespace App\Http\Controllers\Modules\Payment;

use App\Http\Controllers\Api\PhonePe\PhonePeRefundController;
use App\Http\Controllers\Api\PhonePe\PhonePeStatusController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Modules\Processing\ProcessingController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class CallbackController extends Controller
{
    public function paymentCallback(Request $request, $id)
    {
        $response = base64_decode($request->input('response'));
        Log::debug("S2S RESPONSE [" . $id . "] -> " . $response);

        $responseData = json_decode($response);

        $order = DB::table('sale_order')
            ->where('sale_or_no', '=', $id)
            ->first();

        if($order->sale_or_status == env('ORDER_TICKET_GENERATED')){
            return response([
               'status' => false,
               'response' => "Ticket already generated by Payment Status"
            ]);

        }

        Log::debug("ORDER DETAILS -> " . json_encode($order));

        if ($responseData->success) {

            if ($responseData->code == "PAYMENT_SUCCESS") {

                DB::table('sale_order')
                    ->where('sale_or_no', '=', $order->sale_or_no)
                    ->update([
                        'pg_txn_no' => $responseData->data->providerReferenceId,
                        'sale_or_status' => env('ORDER_PAYMENT_SUCCESS')
                    ]);

                $getTkt = new ProcessingController();
                $getTkt->init($order);

            } else {

                DB::table('sale_order')
                    ->where('sale_or_no', '=', $order->sale_or_no)
                    ->update([
                        'sale_or_status' => env('ORDER_PAYMENT_FAILED')
                    ]);

            }

        } else {

            DB::table('sale_order')
                ->where('sale_or_no', '=', $order->sale_or_no)
                ->update([
                    'sale_or_status' => env('ORDER_PAYMENT_FAILED')
                ]);

        }
    }

    public function SetStatus(){
        $tkts = DB::table('sale_order')
            ->where('sale_or_status','=',env('ORDER_TICKET_GENERATION_FAILED'))
            ->where('mm_ms_acc_id','!=', null)
            ->whereDate('txn_date','>=',date('2022-12-06'))
            ->get();

        foreach ($tkts as $tkt){

            DB::table('sale_order')
                ->where('sale_or_no','=',$tkt->sale_or_no)
                ->update([
                    'sale_or_status' => env('ORDER_TICKET_GENERATED')
                ]);

            $data = file_get_contents("php://input");
            $file = 'StatusChangeLog.txt';
            $data =  "\n$tkt->sale_or_no\n".json_encode($tkt);
            file_put_contents($file, $data, FILE_APPEND | LOCK_EX);
        }


        return response([
           'status' => true,
           'response' => $tkts
        ]);

    }


//////Full Refund in Case ticket Generation Failed
    public function fullRefund(){

        $orders = DB::table('sale_order')
            ->where('sale_or_status','=',env('ORDER_TICKET_GENERATION_FAILED'))
            ->whereDate('txn_date','>=',date('2022-12-10'))
            ->get();

        foreach ($orders as $order) {
            $paymentStatus = new PhonePeStatusController();
            $response = $paymentStatus->getPaymentStatus($order);

            if ($response->code == "PAYMENT_SUCCESS") {


                $user_data = DB::table('users')
                    ->where('pax_id', '=', $order->pax_id)
                    ->first();


                // GENERATING REFUND ORDER
                $refund_order_id = "RFATEK" . $user_data->pax_id . strtoupper(dechex($user_data->cust_mobile + time()));

                // CREATING REFUND ORDER
                DB::table('refund_order')
                    ->insert([
                        'ref_or_no' => $refund_order_id,
                        'sale_or_id' => $order->sale_or_id,
                        'pax_id' => $order->pax_id,
                        'unit' => $order->unit,
                        'ref_amt' => $order->total_price,
                        'ref_chr' => "0",
                        'ref_or_status' => env('ISSUE'),
                        'txn_date' => now()
                    ]);


                $ref_res = new PhonePeRefundController();
                $ref_response = $ref_res->init($order, $refund_order_id, $order->total_price);

                $data = file_get_contents("php://input");
                $file = 'PhonepeFullRefundLog.txt';
                $data = "\n$order->sale_or_no\n" . json_encode($ref_response);
                file_put_contents($file, $data, FILE_APPEND | LOCK_EX);


                if ($ref_response->success) {
                    DB::table('refund_order')
                        ->where('sale_or_id', '=', $order->sale_or_id)
                        ->update([
                            'ref_or_status' => env('REFUND'),
                            'pg_txn_no' => $ref_response->data->transactionId,
                        ]);

                    DB::table('sale_order')
                        ->where('sale_or_no', '=', $order->sale_or_no)
                        ->update([
                            'sale_or_status' => env('ORDER_REFUNDED')
                        ]);


                } else {

                    DB::table('sale_order')
                        ->where('sale_or_no', '=', $order->sale_or_no)
                        ->update([
                            'sale_or_status' => env('ORDER_REFUND_FAILED')
                        ]);

                }


            } else {

                DB::table('sale_order')
                    ->where('sale_or_no', '=', $order->sale_or_no)
                    ->update([
                        'sale_or_status' => env('ORDER_PAYMENT_FAILED')
                    ]);

            }
        }


    }


}
